
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - store-backend
    restart: always

  backend:
    build: .
    container_name: backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_URL=${S3_URL}
      - USERNAME_YOOKASSA=${USERNAME_YOOKASSA}
      - SEKRET_KEY_YOOKASSA=${SEKRET_KEY_YOOKASSA}
      - REDIRECT_URL_YOOKASSA=${REDIRECT_URL_YOOKASSA}
    depends_on:
      - db
    ports:
      - "1200:1200"
    networks:
      - store-backend
    restart: always

volumes:
  postgres_data:

networks:
  store-backend:
    driver: bridge